[package]
name = "provenance-machine"
version = "0.1.0"
description = "Cryptographic provenance infrastructure on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "provenance_machine"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.31.1"
