const {Connection,PublicKey,clusterApiUrl,SystemProgram,Transaction,TransactionInstruction}=solanaWeb3;
const PROGRAM_ID=new PublicKey("ProveNance11111111111111111111111111111111");
const connection=new Connection(clusterApiUrl("devnet"),"confirmed");
let wallet=null,selectedFile=null,selectedHash=null;
const $=id=>document.getElementById(id);
async function sha256(file){const d=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function short(v){return v?v.slice(0,8)+"…"+v.slice(-8):"—"}
function bytes(n){return n<1024?n+" B":n<1048576?(n/1024).toFixed(1)+" KB":(n/1048576).toFixed(2)+" MB"}
async function selectFile(file){if(!file)return;selectedFile=file;$('fileState').textContent='HASHING LOCALLY';selectedHash=await sha256(file);$('fileName').textContent=file.name;$('fileSize').textContent=bytes(file.size);$('fileHash').textContent=selectedHash;$('fileInfo').classList.remove('hidden');$('fileState').textContent='READY';$('verifyBtn').disabled=false;$('anchorBtn').disabled=!wallet;$('status').textContent='HASH READY';}
$('fileInput').addEventListener('change',e=>selectFile(e.target.files[0]));
const dz=$('dropZone');['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.style.borderColor='#fff'}));['dragleave','drop'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.style.borderColor=''}));dz.addEventListener('drop',e=>selectFile(e.dataTransfer.files[0]));
async function connectWallet(){if(!window.solana?.isPhantom){alert('Install Phantom Wallet, then reload this page.');return}try{const r=await window.solana.connect();wallet=r.publicKey;$('walletAddress').textContent=short(wallet.toBase58());$('walletState').textContent='WALLET CONNECTED';$('connectBtn').textContent='WALLET CONNECTED';$('anchorBtn').disabled=!selectedHash}catch(e){console.error(e)}}
$('connectBtn').addEventListener('click',connectWallet);
function artifactPda(hashBytes){return PublicKey.findProgramAddressSync([new TextEncoder().encode('provenance'),wallet.toBytes(),hashBytes],PROGRAM_ID)[0]}
async function anchor(){if(!wallet||!selectedHash)return;$('anchorBtn').disabled=true;$('status').textContent='BUILDING TRANSACTION';try{const hashBytes=new Uint8Array(selectedHash.match(/.{2}/g).map(x=>parseInt(x,16)));const version=Math.max(1,Number($('version').value)||1);const versionBytes=new Uint8Array(8);new DataView(versionBytes.buffer).setBigUint64(0,BigInt(version),true);const discriminator=new Uint8Array([0,0,0,0,0,0,0,0]);const data=new Uint8Array([...discriminator,...hashBytes,...versionBytes]);const pda=artifactPda(hashBytes);const ix=new TransactionInstruction({keys:[{pubkey:pda,isSigner:false,isWritable:true},{pubkey:wallet,isSigner:true,isWritable:true},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false}],programId:PROGRAM_ID,data});const latest=await connection.getLatestBlockhash();const tx=new Transaction({recentBlockhash:latest.blockhash,feePayer:wallet}).add(ix);const signed=await window.solana.signTransaction(tx);const sig=await connection.sendRawTransaction(signed.serialize());await connection.confirmTransaction({signature:sig,blockhash:latest.blockhash,lastValidBlockHeight:latest.lastValidBlockHeight},'confirmed');$('status').textContent='ANCHORED';$('txResult').classList.remove('hidden');$('txResult').innerHTML='TRANSACTION<br><code>'+sig+'</code><br><br>RECORD PDA<br><code>'+pda.toBase58()+'</code>';}catch(e){console.error(e);$('status').textContent='TRANSACTION FAILED';$('txResult').classList.remove('hidden');$('txResult').textContent=e.message||String(e)}finally{$('anchorBtn').disabled=false}}
$('anchorBtn').addEventListener('click',anchor);
$('verifyBtn').addEventListener('click',async()=>{if(!selectedFile||!wallet)return;$('verifyResult').className='verify-result';$('verifyResult').textContent='CHECKING ON-CHAIN RECORD…';try{const current=await sha256(selectedFile);const hashBytes=new Uint8Array(current.match(/.{2}/g).map(x=>parseInt(x,16)));const pda=artifactPda(hashBytes);const account=await connection.getAccountInfo(pda);if(!account){$('verifyResult').className='verify-result fail';$('verifyResult').textContent='NO PROVENANCE RECORD FOUND FOR THIS ARTIFACT.';return}$('verifyResult').className='verify-result success';$('verifyResult').innerHTML='PROVENANCE RECORD FOUND<br>PDA: <code>'+pda.toBase58()+'</code><br><br>THE CURRENT FILE HASH RESOLVES TO AN ON-CHAIN RECORD.'}catch(e){$('verifyResult').className='verify-result fail';$('verifyResult').textContent=e.message||String(e)}});
window.addEventListener('load',async()=>{if(window.solana?.isConnected){try{const r=await window.solana.connect({onlyIfTrusted:true});wallet=r.publicKey;$('walletAddress').textContent=short(wallet.toBase58());$('walletState').textContent='WALLET CONNECTED'}catch{}}});
